### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by SAMAPP100** [SAMAPP100/HangMan#2]

**Comment by AshiraFriedman** [comment]
Very nice!
The wireframe picture is big, please make it smaller so that the whole image can be seen at once on the screen on github

**Comment by SAMAPP100** [comment]
I'm  not sure exactly what you mean, maybe it depends on the size of the screen.

**Comment by AshiraFriedman** [comment]
![Screenshot (72)](https://user-images.githubusercontent.com/77624864/224124651-2ef5aee4-4f66-4eab-b1e9-bc6e1d84f1ba.png)

**Comment by AshiraFriedman** [comment]
This is how the wireframe image appears on my screen.  Does it appear differently on yours?

**Comment by SAMAPP100** [comment]
![Screenshot 2023-03-09 194702](https://user-images.githubusercontent.com/93601811/224137698-4932bebd-0379-442b-85c6-5ab74fe6c634.jpg)

**Comment by AshiraFriedman** [comment]
Okay, on your screen it looks good, I'm not sure what's causing it to be so big on my screen, but it's fine to just leave it as is.
